# Generated by Django 4.2 on 2023-06-13 00:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('aluno', models.CharField(max_length=200, validators=[core.models.validate_min_length], verbose_name='aluno')),
                ('professor', models.CharField(choices=[('Nilton Cesar Sacco', 'Nilton Cesar Sacco'), ('Orlando Saraiva Júnior', 'Orlando Saraiva Júnior'), ('Thiago Mendes', 'Thiago Mendes'), ('Sama Rouani', 'Sama Rouani')], max_length=200, verbose_name='professor')),
                ('disciplina', models.CharField(choices=[('Banco de Dados Relacional', 'Banco de Dados Relacional'), ('Desenvolvimento Web III', 'Desenvolvimento Web III'), ('Banco de Dados Não Relacional', 'Banco de Dados Não Relacional'), ('Técnicas de Programação II', 'Técnicas de Programação II')], max_length=200, verbose_name='disciplina')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
        ),
    ]
