# Generated by Django 4.1.2 on 2023-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listamodels',
            name='disciplina',
            field=models.CharField(choices=[('Banco de Dados Relacional', 'Banco de Dados Relacional'), ('Desenvolvimento Web III', 'Desenvolvimento Web III'), ('Banco de Dados Não Relacional', 'Banco de Dados Não Relacional'), ('Técnicas de Programação II', 'Técnicas de Programação II')], max_length=200, verbose_name='disciplina'),
        ),
    ]
